@echo off
..\..\tools\kmake.py kernel.py
..\..\tools\kmake.py kavutil.py
..\..\tools\kmake.py cryptolib.py
..\..\tools\kmake.py eicar.py
..\..\tools\kmake.py dummy.py
..\..\tools\kmake.py emalware.py
..\..\tools\kmake.py macro.py
..\..\tools\kmake.py hwp.py
..\..\tools\kmake.py pe.py
..\..\tools\kmake.py elf.py
..\..\tools\kmake.py ole.py
..\..\tools\kmake.py html.py
..\..\tools\kmake.py script.py
..\..\tools\kmake.py pdf.py
..\..\tools\kmake.py olenative.py
..\..\tools\kmake.py attach.py
..\..\tools\kmake.py zip.py
..\..\tools\kmake.py alz.py
..\..\tools\kmake.py cab.py
..\..\tools\kmake.py nsis.py
..\..\tools\kmake.py kicom.lst

